### ISSUE TITLE
How to handle vulnerability disclosure?

### ISSUE THREAD

**Issue by ghelleks** [18F/open-source-policy#20]
The Practice document should probably prescribe some policy for handling undisclosed security vulnerabilities. I can offer [Fedora's policy](https://fedoraproject.org/wiki/Security_Bugs#Embargoed_Security_Issues), and [Red Hat](https://securityblog.redhat.com/2013/01/30/a-minimal-security-response-process/)'s process, but you have many options.

Maybe in the Practice document, or in another document about software development practices generally, I'd think about who's responsible for maintaining CVEs (if those are necessary), how one should organize a security response in general, and how you communicate remediations to the user base.

I'm sure your DAA would have opinions about all of this.

**Comment by alex** [comment]
FWIW, I've tried to outline a process here: https://alexgaynor.net/2013/oct/19/security-process-open-source-projects/ this describes effectively what Django's process is; approximately the same material in talk form: http://www.heavybit.com/library/video/2014-10-14-alex-gaynor

**Comment by Klortho** [comment]
:+1:

Pinging @NoahKunin again.

**Comment by s7726** [comment]
Something like a security.txt in the repo (and the site if it is/has one)?
https://securitytxt.org/

**Comment by adborden** [comment]
Disclosure policy:
https://github.com/18F/vulnerability-disclosure-policy
