### ISSUE TITLE
Engaging the Public via GitHub w/ 'help wanted' tags & roadmapped issues

### ISSUE THREAD

**Issue by rebeccawilliams** [18F/open-source-policy#26]
I am not sure if this belongs in the Open Source Policy or is more of a cultural/soft policy, but it'd be great to see 18F by default engage the public with 'help wanted' tags and with straightforward issues that roadmap what needs to be done next, e.g. [Code for America's workflow](https://github.com/codeforamerica/cfapi/issues/166). It'd be great to have the public directly contributing to government projects more.

**Comment by webmaven** [comment]
Is there a doc on starting new repos? If so, a note *there* on which issue tags to create, what they mean/signal, and how/when to use them would probably be useful.

**Comment by janearc** [comment]
tags vary by repo.

**Comment by webmaven** [comment]
> tags vary by repo.

Well, yes, but shouldn't there be *some* fairly standard ones in common (such as ```help-wanted```)?

> I saw it was the convention elsewhere and just started doing it.

All I am suggesting is that the common(est) conventions be documented.

**Comment by rebeccawilliams** [comment]
:+1: to @webmaven's pitch to have the most common tags or *at least* the `help-wanted` tag documented somewhere. This doesn't have to dictate a top down workflow for all projects, but having consistency across the Contributing.md files and use of a `help-wanted` tag can help signal 18F's welcoming of public contributions.

**Comment by gbinal** [comment]
Good ideas - thanks, @webmaven, @rebeccawilliams.

**Comment by gbinal** [comment]
FYI, govcode.org is looking to start integrating the help-wanted tag.  
* http://stage.govcode.org.s3-website-us-east-1.amazonaws.com
* http://stage.govcode.org.s3-website-us-east-1.amazonaws.com/issues
