### ISSUE TITLE
18f-init

### ISSUE THREAD

**Issue by janearc** [18F/open-source-policy#27]
If you create a new repository on Github, you get either a bare repository, or a repository with files that aren't going to be used if you're going to use [`18f-init`](https://github.com/18F/open-source-policy/blob/master/practice.md#how-to-license-18f-repos). Do you think adding additional commands to the shell alias so something like `create-18f-repo` would be useful?

```bash
alias create-repo="mkdir \!* && cd \!* && git init ."
alias insert-license="wget -q https://raw.githubusercontent.com/18F/open-source-policy/master/LICENSE.md"
alias insert-contrib="wget -q https://raw.githubusercontent.com/18F/open-source-policy/master/CONTRIBUTING.md"
alias 18f-init="insert-license && insert-contrib && echo 'Licensed.'"
alias create-18f-repo="crete-repo \!* && 18f-init && git add . && git commit -m 'initial commit' ."
```

In my own experience I think I make a repo in the shell about half the time and on Github half the time, but I don't know what everyone else does.

**Comment by afeld** [comment]
I almost always use command-line. :+1:

**Comment by gbinal** [comment]
FWIW, always through the browser.

**Comment by adelevie** [comment]
:+1: +1:

We're not writing a tool, just providing handy snippets for people to copy from.
