### ISSUE TITLE
Resource to Argue that Secure Agencies are using Open Source

### ISSUE THREAD

**Issue by RobertLRead** [18F/open-source-policy#30]
I was recently question by an executive from the Department of Labor for support for the use of Open Source---in particular, she wanted to know what other agencies were using open source.  I composed (essentially) the following response to her.  I believe something like this could be added as a new document, perhaps as a one-page "Look who is using open source", or something more formal.

Thank you for your question about the use of Open Source in other agencies.  As I mentioned in my off-the-cuff remarks, 18F alone is currently working on open-source projects for the Navy Reserve (and I forgot to mention the Air Force and Treasury, as well as traditionally less security-oriented agencies, such as the Peace Corps.)  In fact, 18F's basic policy is to always use Open Source, in accordance with the OMB's U.S. Digital Services Playbook Play #13, "Default to Open".  A cross-governmental set of open-source policy documents has been collected here. 

However, you may find the following references add gravitas to this position.

A collection of 970 Federal open-source projects specifically hosted at GitHub, which is one of several cloud-based code repository systems, can be found here (prepare to scroll a lot, or narrow your search on the right!): https://www.govcode.org

A different DoD-specific list is the Defense Advanced Research Projects Agency catalog of open-source projects: http://www.darpa.mil/OpenCatalog/index.html

There are two very active email listservs discussing and promoting the use of open source.  You need not subscribe to these listservs to review all the conversations there. For government generally:

https://groups.google.com/forum/?nomobile=true#!forum/government-open-source

And for the military use of open source in particular:

https://groups.google.com/forum/?nomobile=true#!forum/mil-oss

A cross-governmental variety of formal policies in support of open source can be found here: http://18f.github.io/open-source-program/pages/policy_documents/

**Comment by benbalter** [comment]
If it's helpful, here's [the full list of 125+ federal orgs](https://government.github.com/community/#u.s._federal). It may also be worthwhile to pose this question in [github.com/governmnet](https://government-community.githubapp.com/government/best-practices).

**Comment by pammiller0** [comment]
Great info thanks! I will incorporate this into our GSA IAE open source plan.

**Comment by afeld** [comment]
Closing as stale.
