### ISSUE TITLE
Reference the code of conduct in our boilerplate CONTRIBUTING file?

### ISSUE THREAD

**Issue by konklone** [18F/open-source-policy#38]
We have a nice [Code of Conduct](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md) that applies to our open source projects. Should we put a link to it in our [default CONTRIBUTING file](https://github.com/18F/open-source-policy/blob/master/CONTRIBUTING.md), and/or the [little README snippet](https://github.com/18F/open-source-policy/blob/master/README.md#public-domain) some of our projects use?

cc @annalee @leahbannon @jackiekazil

**Comment by jackiekazil** [comment]
:+1:

**Comment by annalee** [comment]
:+1:

**Comment by konklone** [comment]
Cool. I'm remembering that we had a thread about this: https://github.com/18F/code-of-conduct/issues/11 I'll close that too when this is closed, and plan to file a pull request promptly.

**Comment by konklone** [comment]
Will file a PR later, but here's my first pass: https://github.com/cfpb/source-code-policy/compare/gh-pages...18F:code-of-conduct

**Comment by konklone** [comment]
I've opened a PR to resolve this, along with some rewritten language:

https://github.com/18F/open-source-policy/pull/39

**Comment by melodykramer** [comment]
:+1:

**Comment by stvnrlly** [comment]
Any reason to keep this issue open?

**Comment by konklone** [comment]
Seems all good!
