### ISSUE TITLE
Adapt college-choice contributing guidelines to be our new template?

### ISSUE THREAD

**Issue by konklone** [18F/open-source-policy#42]
They put a bunch of work into it and it's pretty sweet:

https://github.com/18F/college-choice/blob/dev/CONTRIBUTING.md

However, it is optimized for websites or repos where prose changes by less technical folks are what is expected. So it's not the ideal CONTRIBUTING.md for all of our projects. Still, maybe we could develop a couple, or modify the college-choice one to work for less or more technical repos?

**Comment by afeld** [comment]
Closing as stale.
