### ISSUE TITLE
Statement about 18F work prior to IAAs

### ISSUE THREAD

**Issue by edmullen** [18F/open-source-policy#50]
In https://github.com/18F/open-source-policy/blob/master/practice.md#delays-and-exceptions, I noticed it's stated: 

> "It's common for 18F to begin work on code before formally signing and completing an "inter-agency agreement" (IAA) with our partner” 

This seems contrary to statements @joshuabailes has made in meetings.

**Comment by joshuabailes** [comment]
Any idea who wrote it and why?

**Comment by edmullen** [comment]
Seems like @konklone did most of the work on this and that the statement quoted above comes from the original team FAQ the page was based on. It was present in the first commit. (Eric, I should have cc'd you initially.)

**Comment by joshuabailes** [comment]
@konklone What does this mean? At first blush, it reads like we start work before we have agreement in place, which we shouldn't do. But I think it may have a different meaning.

**Comment by konklone** [comment]
@joshuabailes We should update the text to clarify this, as we've since done a much better job at communicating how the IAA process governs our work processes to our engineering team than we did in 2014. Want to take an axe to it, or should I?

**Comment by joshuabailes** [comment]
Ed,
Here is the language from our current handbook is:

Under no circumstances does 18F do work without a signed, executed
agreement in place.

The language to change:
"It's common for 18F to begin work on code before formally signing and
completing an "inter-agency agreement" (IAA) with our partner”

New suggested language (without full idea of context)

18F cannot begin work with other agencies without a signed agreement in
place. If you are interested in doing with 18F, please contact 18F at
Inquiries18F@gsa.gov.





Joshua Bailes
18F Acquisitions/Agreements Lead
Joshua.Bailes@gsa.gov
202-550-6659
18F.gsa.gov <https://18f.gsa.gov/>

**Comment by konklone** [comment]
I filed #50, which removes the whole section as unnecessary.
