### ISSUE TITLE
Add guidance for project deprecation

### ISSUE THREAD

**Issue by stvnrlly** [18F/open-source-policy#54]

**Comment by konklone** [comment]
:+1: Any opening thoughts on what the guidance should say?

**Comment by stvnrlly** [comment]
Sure, maybe something like

---
## Deprecating a repository

When a repository is no longer useful, it should be deprecated. This may be because the work has been incorporated into another repository, the project is unmaintained and out-of-date, or some other reason.

In order to preserve repository metadata like pull request discussions and issues, the repository should not be deleted or made private. Instead, a prominent deprecation notice should be added. This notice should include the project's status as deprecated, a reason for the deprecation, and (if applicable) a link to the repository where work is continuing.

The deprecation notice should be added to the top of the project's `README`, and the description field should be changed to reflect the project's status as deprecated.
