### ISSUE TITLE
Reconsider README branch recommendation

### ISSUE THREAD

**Issue by cmc333333** [18F/open-source-policy#56]
The README template asserts a `master`/`develop` workflow which [isn't common](https://github.com/18F/development-guide/tree/master/example_workflows) on 18F projects. We also have [documentation](https://github.com/18F/development-guide/tree/master/git_protocol) which hints at a feature-branch model.

Should we just remove that recommendation for now?

**Comment by konklone** [comment]
Oh, yeah, that seems orthogonal to what this repo is meant to do. Thanks for catching that, I'm a :+1: on axing it.

**Comment by stvnrlly** [comment]
The idea of that section was to encourage projects to give some information on how to interact with the repo, not to prescribe a particular workflow. I think that's useful information that's in line with this repo's goal, so I'd prefer changing it rather than deleting it.

**Comment by konklone** [comment]
What about changing it to be more of a skeleton that the project has to fill out for themselves?

**Comment by cmc333333** [comment]
Another possibility: look for commonalities across existing workflow docs (some folks collected a set earlier: https://github.com/18F/development-guide/tree/master/example_workflows) and create some sort of base `CONTRIBUTING`/what-have-you.

I'm not sure such a document fits this repo well, but it could certainly be in https://github.com/18F/18f-cli or in a handbook, referenced by that cli.

**Comment by stvnrlly** [comment]
I think some sort of skeleton or template sounds lovely. It sounds like that should live elsewhere, so I'll go ahead and re-close this and pick it up in a more appropriate location.
