### ISSUE TITLE
Broken link to National Archive's list of controlled unclassified information

### ISSUE THREAD

**Issue by adborden** [18F/open-source-policy#66]
https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information contains a broken link referring to the complete list of controlled unclassified information which results in a 404.

This is the broken link https://www.archives.gov/cui/registry/category-list.html

**Comment by brittag** [comment]
Thanks for catching this! I checked https://www.archives.gov/cui to find a new link for this list, and that page is still linking to this 404 page - but it looks like https://www.archives.gov/cui/registry will work as a replacement. I'll file a PR.
