### ISSUE TITLE
Write dedicated doc on how to acquire open-source 

### ISSUE THREAD

**Issue by NoahKunin** [18F/open-source-policy#8]
Inclusive of market research, procuring support services, ensure IDIQs produce/use open-source, etc etc etc.

Cross ref with issue #1 

cc @rjmajma @konklone

**Comment by konklone** [comment]
@NoahKunin @vzvenyach @adelevie Do we have some good example language from the Agile BPA we can use to resolve the issue?

**Comment by afeld** [comment]
Closing as stale.

**Comment by djwhitten** [comment]
I have no doubt it is stale.
I don't know if the sample language has been written.
I expect if it has not, that it is still needed.
Dave

**Comment by vzvenyach** [comment]
@afeld @djwhitten happy to revive it in a new issue. happily, there's a lot of potential prior art now. :D

**Comment by afeld** [comment]
Yep, just "stale" in the "we don't plan to get to this in the near future" sense. Anyone, feel free to drop links to other resources in this thread.
