### ISSUE TITLE
Include link to GSA's open source policy

### ISSUE THREAD

**Issue by adborden** [18F/open-source-policy#87]
GSA created an open source policy based on our fork. We probably want to acknowledge that the GSA policy exists and is different than 18F.

> GSA maintains it's own [Open Source Policy](https://open.gsa.gov/oss-policy/) and [Guidance repository](https://github.com/GSA/open-source-policy).

**Comment by dylanirlbeck** [comment]
@adborden So I see a link to the GSA Open Source Policy in the [Further Reading](https://github.com/18F/open-source-policy/blob/master/policy.md#further-reading) section of the policy. Did you have something else in mind?

**Comment by adborden** [comment]
Nope, sounds like this is complete.
