### ISSUE TITLE
create default "community health" files

### ISSUE THREAD

**Issue by afeld** [18F/open-source-policy#91]
https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

**Comment by bryanweast** [comment]
I almost committed suicide. Cognitive computing isn't a fucking toy.

**Comment by its-a-lisa** [comment]
I believe I did this ... https://github.com/18F/.github/tree/master

**Comment by afeld** [comment]
Great! We can make smaller follow-up issues as needed.
