### ISSUE TITLE
add information about Controlled Unclassified Information (CUI)

### ISSUE THREAD

**Issue by afeld** [18F/open-source-policy#93]
We should reference it in the [protecting sensitive information](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information) section.

- https://insite.gsa.gov/cui
- https://www.archives.gov/cui
- https://www.federalregister.gov/documents/2016/09/14/2016-21665/controlled-unclassified-information
- https://obamawhitehouse.archives.gov/the-press-office/2010/11/04/executive-order-13556-controlled-unclassified-information

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
