### ISSUE TITLE
TTS-wide open source policy

### ISSUE THREAD

**Issue by afeld** [18F/open-source-policy#94]
_Putting in this repository for lack of a better place._

User story:

- As a member of TTS, I want to know what rules to follow around open source.

Existing policies:

- [18F](https://github.com/18F/open-source-policy/blob/master/policy.md)
- [OPP (draft)](https://docs.google.com/document/d/1Q9SLQmlUxnnJCi4sgE2_Ttl1E7Y8KKgGJHn5TpOCY3c/edit)
- [GSA](https://www.gsa.gov/directives-library/gsa-open-source-software-oss-policy-21071-cio)

**Comment by thecapacity** [comment]
Here's an initial draft from the code.gov team, building on 18F's; https://docs.google.com/document/d/1Q9SLQmlUxnnJCi4sgE2_Ttl1E7Y8KKgGJHn5TpOCY3c/edit

**Comment by thecapacity** [comment]
More general Q - if we want to say solutions are `(1) open source` and `(2) open data` and `(3)...`, `(x)` is that 1 combined policy (maybe with pointers) or 1 checklists with n policies/write-ups?

i.e. how do we prevent reading or link overload?

**Comment by afeld** [comment]
A balance with the policies being too long and having scope creep, I suppose.

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
