### ISSUE TITLE
License to also cover external contributions?

### ISSUE THREAD

**Issue by jlaura** [18F/open-source-policy#95]
We are working on bring our OSS license inline with current leading government practices. This means migrating off the UnLicense that we had previously been using. The templated language and use of CC0 1.0 is awesome.

Should we be modifying?

> As a work of the United States government, this project is in the public domain within the United States of America.

The project is primarily developed by U.S. gov employees, but we most definitely have external contributors. Right now, we have a template on PRs with the following language and a checkbox where the PR author can place the contribution into the public domain. Is this sufficient and how might this language / contribution model impact the above quoted line from the license file.

-------
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [ ]  I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by afeld** [comment]
Not A Lawyer, but I would only use the "work of the United States government" if the project is primarily "owned"/managed by the government.

> I dedicate any and all copyright interest in this software to the public domain

You might consider adding that to the pull request template, as it's essentially a Contributor License Agreement.

**Comment by leebrian** [comment]
I am also not a lawyer, here's the [default language CDC uses](https://github.com/CDCgov/template#contributing-standard-notice) for our OSS projects...

> Anyone is encouraged to contribute to the repository by forking and submitting a pull request. (If you are new to GitHub, you might start with a basic tutorial.) By contributing to this project, you grant a world-wide, royalty-free, perpetual, irrevocable, non-exclusive, transferable license to all users under the terms of the Apache Software License v2 or later.

We include a public domain declaration and projects include an applicable license. Most are ASLv2. For non ASLv2 projects, the above language is modified to meet the language.

**Comment by jlaura** [comment]
@afeld Input appreciated.

I am in DOI/USGS - is the license information in this repo and on source code.coi.gov the current policy governing OS development by the gov? Information is a little scattered across websites and repositories so just trying to parse through it all.

**Comment by afeld** [comment]
> is the license information in this repo…the current policy governing OS development by the gov?

Nope! This repository is only applicable to 18F (and [maybe soon TTS](https://github.com/18F/open-source-policy/issues/94)), though we encourage its reuse by other agencies.

**Comment by IanLee1521** [comment]
I'm not aware of any "all of government policy", but definitely point to 18F fairly regularly. On the one hand I believe that having a consistent policy across government could be helpful, but in reality, I don't think it's particularly likely to get all the various agency lawyers and IP folks on the same page...

**Comment by corizarek** [comment]
The White House/OMB published a [Federal Source Code policy](https://sourcecode.cio.gov/) in August 2016 that is an all of government policy. The Code.gov team sitting under TTS formed out of that policy and implementation effort. Your instinct is spot on -- it was indeed a heavy lift to get all the agency lawyers and IP folks on the same page (and navigate conversations and comments from industry) and took about two years from start to finish for this policy process alone.

**Comment by IanLee1521** [comment]
Yep, I've been involved with that policy work and Code.gov since 2016.

While it is government wide though, it never got to some of the more "implementation" details and doesn't prescribe those things (which license to use, how to host code, how to generate inventories, etc) ("more like guidelines than actual rules")

**Comment by corizarek** [comment]
Got it - when I saw your post: "I'm not aware of any 'all of government policy'" it sounded like you might not have been aware of the policy. Agree there's still a lot to do re implementation and glad there's a dedicated team on it.

**Comment by leebrian** [comment]
I wish the source code policy addressed contributor agreements. Maybe in version 2.

**Comment by IanLee1521** [comment]
Definitely agree.

**Comment by jlaura** [comment]
We ended up going with a CC0-1.0 with a slightly modified header text on the project for now. We'll have to work on getting this cleared through our normal channels, but this should conform with what we are seeing here (many thanks for posting these licenses).

```
Unless otherwise noted, this project is in the public domain in the
 United States.

  It contains materials that originally came from the United States
 Geological Survey, an agency of the United States Department of
 Interior.  For more information on their copyright policies, see
 https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits

  It also contains materials from contributors that have waived their
 copyright interest to the public domain.

  Additionally, the authors waive copyright and related rights in the
 work worldwide through the CC0 1.0 Universal public domain dedication.

<Then the standard CC0-1.0 brief.>
```

Thanks all for the conversation. This is an interesting journey working through OS licensing.

**Comment by afeld** [comment]
Closing as stale.
